api_key_env: CROWDIN_KEY
project_identifier: neptune-web-components
commit_message: 'chore: new translations ✨'
append_commit_message: false
files:
  - source: packages/components/lang/en.json
    translation: /packages/components/lang/%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        fr: fr
        hu: hu
        es-ES: es
        tr: tr
        en-GB: en
        pt-BR: pt
        it: it
        de: de
        ru: ru
        pl: pl
        ro: ro
        ja: ja
        zh-HK: hk
        cs: cs
        id: id
    update_option: update_as_unapproved
