files:
  - source: /packages/dynamic-flows/src/i18n/messages.json
    translation: /packages/dynamic-flows/src/i18n/%file_name%_%two_letters_code%.%file_extension%
    languages_mapping:
      two_letters_code:
        zh-HK: zh_HK
    update_option: update_as_unapproved