# Confirm that the config file si valid:
# https://circleci.com/docs/2.0/local-cli/

version: 2

aliases:
  - &workspace-root ~/neptune

  - &container
    working_directory: *workspace-root
    docker:
      - image: circleci/node:lts

  - &attach-workspace
    attach-workspace:
      at: *workspace-root

  - &persist-workspace
    persist_to_workspace:
      root: .
      paths:
        - '*'

  - &install
    name: Install dependencies
    command: yarn install --frozen-lockfile

  - &build
    name: Build packages
    command: yarn build

  - &build-docs
    name: Build docs
    command: yarn docs:build

  - &deploy-docs
    name: Deploy docs
    command: yarn docs:deploy

  - &deploy-docs-for-branch
    name: Deploy docs for branch
    command: yarn docs:deploy-for-branch

  - &lerna-publish
    name: Publish packages
    command: npx lerna publish -m "[skip ci] Release" --yes

  - &lint
    name: Lint packages
    command: yarn lint:check

  - &conventional-commit-lint
    name: Conventional Commits check
    command: npx commitlint -f $(git rev-parse master) -V

  - &get-first-commit-hash
    name: Conventional Commits check
    command: |

  - &test
    name: Test packages
    command: yarn test

  - &add-npm-release-token
    name: Set NPM publish token
    command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc

  - &set-github-credentials
    name: Set github credentials
    command: |
      mkdir -p ~/.ssh
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git config --global user.email "circleci@transferwise.com"
      git config --global user.name "CircleCI"

jobs:
  install:
    <<: *container
    steps:
      - checkout
      - run: *install
      - *persist-workspace

  build:
    <<: *container
    steps:
      - *attach-workspace
      - run: *build
      - *persist-workspace

  test:
    <<: *container
    steps:
      - *attach-workspace
      - run: *lint
      - *persist-workspace

  deploy-docs-to-root:
    <<: *container
    steps:
      - *attach-workspace
      - run: *build-docs
      - run: *set-github-credentials
      - run: *deploy-docs
      - *persist-workspace

  deploy-docs-for-branch:
    <<: *container
    steps:
      - *attach-workspace
      - run: *build-docs
      - run: *set-github-credentials
      - run: *deploy-docs-for-branch
      - *persist-workspace

  conventional-commit-lint:
    <<: *container
    steps:
      - *attach-workspace
      - run: *conventional-commit-lint

  publish:
    <<: *container
    steps:
      - *attach-workspace
      - run: *set-github-credentials
      - run: *add-npm-release-token
      - run: *lerna-publish
      - *persist-workspace

workflows:
  version: 2
  build-deploy-release:
    jobs:
      - install:
          context: frontend-build
          filters:
            branches:
              ignore: gh-pages

      - build:
          context: frontend-build
          filters:
            branches:
              ignore: gh-pages
          requires:
            - install

      - test:
          requires:
            - build

      - deploy-docs-to-root:
          context: frontend-build
          requires:
            - test
          filters:
            branches:
              only: master

      - deploy-docs-for-branch:
          context: frontend-build
          requires:
            - test
          filters:
            branches:
              ignore:
                - gh-pages
                - master

      - conventional-commit-lint:
          context: frontend-build
          requires:
            - install
          filters:
            branches:
              ignore:
                - gh-pages

      - publish:
          context: frontend-deploy-library
          requires:
            - test
          filters:
            branches:
              only: master
