defaults: &defaults
  working_directory: ~/neptune-css
  docker:
    - image: circleci/node:lts

# Install dependencies
# TODO: Test if CSS is valid and can compile, maybe also lint / format CSS 
# Build dist CSS
# Publish on NPM as a public package (only for master branch) 
# Relese on github (only for master branch)

version: 2
jobs:
  install: 
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build dist CSS
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  publish:
    <<: *defaults
    steps:
      - run:
          name: Setup npm token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN_PUBLISH" >> ~/.npmrc
      - attach_workspace:
          at: .
      - run:
          name: Bundle dist CSS
          command: npm run build
      - run:
          name: Publish on npm
          command: npm publish --access=public

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release to GitHub
          command: |
            mkdir ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            npm run release-to-github

workflows:
  version: 2
  build-and-publish:
    jobs:
      - install
      - build:
          requires:
              - install
      - publish:
          context: frontend-publish
          requires:
            - build
          filters:
            branches:
              only: master          
      - release:
          context: frontend-publish
          requires:
            - publish
          filters:
            branches:
              only: master
