defaults: &defaults
  working_directory: ~/neptune-css
  docker:
    - image: circleci/node:latest
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build docs
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
workflows:
  version: 2
  build-test-release-and-build-docs:
    jobs:
      - build
